### ISSUE TITLE
Footswitches not working

### ISSUE THREAD

**Issue by nickcent** [bl0b/renoise-xtouch-xctl.xrnx#7]
Footswitches are unresponsive.

**Comment by bl0b** [comment]
Are you using continuous or on/off pedals?
What are your current foot switch settings in the Mixer settings?
Do you see F#8 or G-8 notes coming in on the MIDI dump?

**Comment by nickcent** [comment]
no not continues. ON/OFF triggers. 
Where are the mixer settings? 
Yes, F#8 and G8 on the midi log.

**Comment by nickcent** [comment]
I went into the tool's settings but couldn't see any footswitch field or something.

**Comment by bl0b** [comment]
You can open the program settings by clicking the gear icon to the right of "Mixer" at the bottom of the dialog. There should be 2 settings per foot switch.
The X-Touch seems to dislike continuous pedals in the foot switch jacks so I had to check. Can you download the repo again and test?

![image](https://user-images.githubusercontent.com/138225/67142828-cd101c00-f219-11e9-8b30-1993eefd7ece.png)

**Comment by nickcent** [comment]
I'm sorry I can't see this menu. I tried several things. The tool is the same to me.

**Comment by bl0b** [comment]
OK, you need to download the zip from this address to enjoy the new features:
https://github.com/bl0b/renoise-xtouch-xctl.xrnx/archive/master.zip
Unzip it inside your `%APPDATA%\Renoise\V3.2.0\Scripts\Tools\` directory.
At all times this is the latest version of the tool. It will display as "X-Touch [DEV]" .
You'll also get the almost complete automation page (assigned to `ENCODER ASSIGN / TRACK`) :)

I'll wait for your confirmation to close this issue.

**Comment by nickcent** [comment]
Will test again today. I put it in every other folder but this one. Back with new impressions later on today. Thanks!

**Comment by nickcent** [comment]
The contents of the Zip file is a folder "renoise-xtouch-xctl.xrnx-master". I put this folder in the Tools folder in the Scripts in **V3.2.0** This folder comes up when I go 'Help' in Renoise, and Show the Preferences Folder. 
I then removed the X-Touch tool and I kept the X-Touch [DEV]. 
Now, it sees no tool...

**Comment by nickcent** [comment]
Re-dropped the d**ev.bl0b.X-Touch_0.1.xrnx** into Renoise. Replaced the folder r**enoise-xtouch-xctl.xrnx-master**. 
![Screen Shot 2019-10-20 at 16 13 13](https://user-images.githubusercontent.com/43449628/67160010-8d9a1a80-f354-11e9-9193-683710bd5c2e.png)

**Comment by nickcent** [comment]
I meant to close the window, not the issue. :P 
Please help me install the tool properly from scratch. I'm lost

**Comment by bl0b** [comment]
OK @nickcent 
I got rid of this ViewBuilder id "programs" when I started running into this issue recently, so it is definitely a sign that the 0.1 version is still here and acting up.

Close Renoise, point your Finder to `/Users/Nick/Library/Preferences/Renoise/V3.2.0/Scripts/Tools/`, and delete any directory with the name X-Touch in it. Then, you can unzip the tool, rename the tool directory `dev.bl0b.X-Touch-DEV.xrnx`, and restart Renoise. That should do it. The directory renaming is because I chose the repo name a bit too early in the project, and Renoise is very specific about this. One upside of this is that the released version and the dev version can coexist in Renoise.

Ideally, to easily update to the most recent version between releases and if a little bit of commandline doesn't scare you (I'll give you all the commands you need to know below), you should install git (very easy to do on Mac).
https://www.atlassian.com/git/tutorials/install-git

Then, instead of unzipping the tool you downloaded from github, you would open up a terminal and paste:

`git clone https://github.com/bl0b/renoise-xtouch-xctl.xrnx.git /Users/Nick/Library/Preferences/Renoise/V3.2.0/Scripts/Tools/dev.bl0b.X-Touch-DEV.xrnx`

The command above is equivalent to downloading and unzipping and into the proper directory, with the added bonus that you can update at any time by pasting:
`cd /Users/Nick/Library/Preferences/Renoise/V3.2.0/Scripts/Tools/dev.bl0b.X-Touch-DEV.xrnx && git pull`

**Comment by nickcent** [comment]
Alright! I did check the new improvements after managing to reinstall the tool. Thank you for the instructions, although I couldn't do the git thing. I installed ok and then pasted the command to git clone https... and it says that the destination folder is not empty and such such.
Now on to the issues...

**Comment by nickcent** [comment]
Footswitches are working and the preferences kick ass!
